#!/bin/sh
# Run this to generate all the initial makefiles, etc.

# This was once upon a time taken from GTK or glib or gimp

[ -f gen-functions ] || { echo "Unable to find gen-functions"; exit 1; }
. gen-functions

######################################################################
# Autogen

initialize "PROJECT" "-d" "src/test"

check_prog "autoconf" "autoconf --version" "2.53" "rebuild configure" \
           "ftp://ftp.gnu.org/pub/gnu/autoconf/"
check_prog "automake" "automake --version" "1.6" "rebuild Makefiles" \
           "ftp://ftp.gnu.org/pub/gnu/automake/"
check_prog "libtool" "libtool --version" "1.4.2" "rebuild library information" \
           "ftp://ftp.gnu.org/pub/gnu/libtool/"
check_cc
checks_or_die

generate

finalize "$@"
