#!/bin/sh

echo -n "WARNING: Cleaning out everything, proceed? (yes/no) "
read yn

if [ "$yn" != "yes" ]; then
    exit 1
fi

if [ -e Makefile ]; then
    echo "making maintainer-clean..."
    make maintainer-clean 2>&1 > /dev/null
fi

echo "cleaning out Makefile.in's..."
find . -name "Makefile.in" -exec rm {} \;

echo "cleaning out backups..."
find . -name '*~' -exec rm {} \;

echo "cleaning out symlinks..."
find . -type l -exec rm {} \;

echo "cleaning out other..."
rm -rf autom4te.cache
rm -f aclocal.m4 defs.h.in configure config.log config.status

echo -n "Make a tarball? (y/n) "
read yn

if [ "$yn" = "y" ]; then
    DIR="`pwd`"
    cd ..
    rm -f unity.tar.gz
    tar cvf unity.tar unity-base
    gzip -9 unity.tar
    cd $DIR
fi
